### PR TITLE
Enable compiler detection only if not added as subproject

### PR DESCRIPTION
**Pull request by havogt**
Compiler detection is dangerous if this project is added via add_subdirectory() or FetchContent as it tries to enable Languages which might be disabled on purpose in the super-project.
Compiler detection is disabled if used as a subproject.

### CODE REVIEW

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
launch jenkins

**Review by lukasm91 — APPROVED** [review]
I'm still not 100% sure about what should be options and what should be variables... same argument would hold for `CPP_BINDGEN_REQUIRE_TEST*`. But I think for the moment this is okay, we can learn from this state and see if this was the right choice. `REQUIRE_TEST` maybe is okay as an option because a user at some point might want to add fortran-support for his tests...

**Comment by havogt** [comment]
launch jenkins

**Pull request merged**
