### PR TITLE
Rename all `gen` to `bindgen`

### PR DESCRIPTION
**Pull request by havogt**

### CODE REVIEW

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
@lukasm91 I requested your review, but feel free to take this unreviewed. Tests should catch naming issues.

**Comment by havogt** [comment]
I saw there are still some mentions of `c_bindings`. Will fix them now.

**Comment by havogt** [comment]
launch jenkins

**Review by lukasm91 — CHANGES_REQUESTED** [review]
Some comments remaining:
```
 > grep -re "\bgen_"
include/cpp_bindgen/array_descriptor.h:    // TODO: add support for strides, bounds end type gen_fortran_array_descriptor
include/cpp_bindgen/export.hpp: *         (`gen_handle*`) which should be released by calling `void bindgen_release(gen_handle*)` function;
include/cpp_bindgen/export.hpp: *       - classes (and structures) and references or pointers to them are transformed to `gen_handle*`;
include/cpp_bindgen/export.hpp: *         (`gen_handle*`) which should be released by calling `void bindgen_release(gen_handle*)` function;
include/cpp_bindgen/export.hpp: *       - classes (and structures) and references or pointers to them are transformed to `gen_handle*`;
```

I didn't check all the changes, but only grepped for missing renames ;-)

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
There is probably one last renaming I'd like to do: currently the prefix is `bindgen`/`BINDGEN` except for the cmake functions `cpp_bindgen_enable_fortran_library` and `cpp_bindgen_add_library`. I think it makes sense to remove it there as well?!

Anyway, I'd like to do this change in a separate PR.

**Pull request merged**
